    name: Create signed git commit sbom

    on: push

    env:
      LOGICAL_APP_NAME: Demo-Integration # The app name all these SBOMs will be assosiated with
      APP_VERSION: 0.0.1# The app version all these SBOMs will be assosiated with
      # SBOM Author meta data - Optional
      AUTHOR_NAME: Adam-Gordon 
      AUTHOR_EMAIL: adam@scribesecurity.com
      AUTHOR_PHONE: 12345 

    jobs:
      build:
        runs-on: ubuntu-latest

        permissions:
          id-token: write # workload identity access needed for signing using sigstore-github 

        steps:
        - uses: actions/checkout@v3

        - name: Generate signed git SBOM
          uses: scribe-security/action-bom@master
          with:
            target: 'git:.'
            scribe-enable: true
            product-key: ${{ github.repository }}
            scribe-client-id: ${{ secrets.CLIENT_ID }}
            scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
            app-name: $LOGICAL_APP_NAME
            app-version: $APP_VERSION
            author-name: $AUTHOR_NAME
            author-email: $AUTHOR_EMAIL
            author-phone: $AUTHOR_PHONE
            label: is_git_commit
            format: attest
